### ISSUE TITLE
copied your code and PR'd

### ISSUE THREAD

**Issue by cottrell** [lawlesst/sparql-dataframe#1]
A bit of extra stuff too. Would be interested if maybe you know that the type conversion there is too fragile to be useful (it works in my one case that I tried). 

https://github.com/RDFLib/sparqlwrapper/pull/112

**Comment by lawlesst** [comment]
Interesting. Thanks for the heads up. 

I hadn't really thought about passing types from SPARQL to pandas. The code I posted will use pandas internal mechanism for inferring types. Not sure what is a better approach and could depend on the number of rows you are trying to load at once.
