### ISSUE TITLE
Add support for POST method

### ISSUE THREAD

**Issue by marijane** [lawlesst/sparql-dataframe#4]
First off, thank you for this very useful library, @lawlesst!

I have been using Blazegraph as my triplestore, which requires using POST instead of GET for very large queries as well as some custom HTTP headers.  

I've modified the get_sparql_dataframe function in my venvs to add the following between lines 18 and 19:
```
    sparql.setOnlyConneg(True)
    sparql.addCustomHttpHeader("Content-type", "application/sparql-query")
    sparql.addCustomHttpHeader("Accept", "text/csv")
    sparql.setMethod(POST)
    sparql.setRequestMethod(POSTDIRECTLY)
```
Could you incorporate this into the package?  Perhaps by adding an optional "post" parameter that defaults to False and that could be used to wrap the above lines in a conditional, to preserve backward compatibility?

**Comment by marijane** [comment]
And the SPARQLWrapper import needs to be updated to:

`from SPARQLWrapper import SPARQLWrapper, CSV, SELECT, POST, POSTDIRECTLY`

... which might be enough for me to get this working and make a pull request.

**Comment by lawlesst** [comment]
Thanks @marijane. Adding `POST` makes sense. I've merged your change and added Wikidata test cases. 

I think POST should be the default, now that you mention it, but DBPedia wasn't returning results when I switched to that so I'll leave it as defaulting to `GET` for now.
