### ISSUE TITLE
AttributeError: module 'pandas.compat' has no attribute 'StringIO'

### ISSUE THREAD

**Issue by mglatz** [lawlesst/sparql-dataframe#6]
Hi, I get this error on every query, including the sample one. I'm on python 3.7 and pandas 1.0.1

**Comment by stefanbischof** [comment]
I get the same error. It seems to be connected to the version of pandas. The error occurs starting with pandas version 0.25, while the same example works perfectly fine with pandas version 0.24.2.

Example code:

```python
import sparql_dataframe
endpoint = "https://dbpedia.org/sparql"
q = "select distinct ?Concept where {[] a ?Concept} LIMIT 100"
df = sparql_dataframe.get(endpoint, q)
```

Error message detail:

```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-92adb562c4eb> in <module>
      7 """
      8 
----> 9 df = sparql_dataframe.get(endpoint, q)

/opt/conda/lib/python3.7/site-packages/sparql_dataframe/sparql_dataframe.py in get_sparql_dataframe(endpoint, query, post)
     27     sparql.setReturnFormat(CSV)
     28     results = sparql.query().convert()
---> 29     _csv = pd.compat.StringIO(results.decode('utf-8'))
     30     return pd.read_csv(_csv, sep=",")

AttributeError: module 'pandas.compat' has no attribute 'StringIO'
```

**Comment by marcus-voss** [comment]
Same problem here.

**Comment by mac389** [comment]
Same problem here.

**Comment by mac389** [comment]
I corrected the issue on my fork.

**Comment by lawlesst** [comment]
Sorry for the delayed response. I didn't see this issue. 

@mac389 has tracked this down and suggested a fix. I have pushed that change to the master branch and to PyPi as version 0.4.

**Comment by tyler-suard-parker** [comment]
I am still having this problem in 2024

**Comment by lawlesst** [comment]
@tyler-suard-parker - SPARQL to dataframe functionality has been added to SPARQLWrapper, [see this code](https://github.com/RDFLib/sparqlwrapper/blob/2a6e2d3ddbc3fe38ca47d6d05f23c9b61ff82366/SPARQLWrapper/sparql_dataframe.py). You may try that to see if resolves this issue.

I'm going to mark this repository "archived" since it's not offering anything more than what has been added to SPARQLWrapper.
